### ISSUE TITLE
PHY is reset on every transfer

### ISSUE THREAD

**Issue by nicolaerosia** [Xilinx/u-boot-xlnx#22]
Hello,

The Ethernet PHY gets reset on every TFTP transfer, slowing down the boot process.

TFTPing Linux to RAM...
Gem.e000b000 Waiting for PHY auto negotiation to complete...... done
Using Gem.e000b000 device
....
Gem.e000b000:7 is connected to Gem.e000b000.  Reconnecting to Gem.e000b000
Gem.e000b000 Waiting for PHY auto negotiation to complete...... done
Using Gem.e000b000 device
...
Gem.e000b000:7 is connected to Gem.e000b000.  Reconnecting to Gem.e000b000
Gem.e000b000 Waiting for PHY auto negotiation to complete....... done
Using Gem.e000b000 device

Best regards,
Nicolae Rosia

**Comment by michalsimek** [comment]
yes. It is there for a long time. There are two approach in the mainline. One is this and second is to run negotiation only once before the first transfer. I choose this approach because you can do stuff between first and second transfer and you can replug cables/switches etc that's why negotiation is required. If you want to speedup this process just use FIT image where all things are in one archive and you are done.
